# Generated by Django 6.1 on 2026-08-18 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='featured',
            field=models.BooleanField(default=False, help_text="Show a 'featured' badge on this project"),
        ),
    ]
