# Generated by Django 6.0.6 on 2026-08-19 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_project_featured'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(default='Bhakra, Himachal Pradesh, India', max_length=120)),
                ('currently_learning', models.CharField(default='JavaScript — closures, async/await, DOM APIs', help_text="Shown in the 'Currently learning' widget on the home page.", max_length=150)),
            ],
            options={
                'verbose_name': 'Site Info',
                'verbose_name_plural': 'Site Info',
            },
        ),
    ]
